server:
  port: 8083
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lorde9030@gmail.com
    password: amyk uynq pvsh cjyd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/notification-api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      

     